# === PASO 1: Instalar dependencias (Bun) ===
FROM oven/bun:1.1-alpine AS deps
WORKDIR /app
COPY package*.json bun.lock* ./
RUN bun install

# === PASO 2: Compilar la aplicación (Node + Turbopack) ===
FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV production

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_TELEGRAM_BOT_USERNAME
ARG NEXT_PUBLIC_CLARITY_PROJECT_ID
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID
ARG NEXT_PUBLIC_USE_STATIC_REFERENCE
ARG NEXT_PUBLIC_CUANDO_API_URL
ARG NEXT_PUBLIC_BONDI_API_URL
ARG NEXT_PUBLIC_PROXY_API_URL
ARG NEXT_PUBLIC_VAPID_PUBLIC
ARG NEXT_PUBLIC_ADSENSE_SLOT_CONSULTAR
ARG NEXT_PUBLIC_ADSENSE_SLOT_ARRIVALS
ARG NEXT_PUBLIC_ADSENSE_SLOT_FAVORITOS
ARG NEXT_PUBLIC_ADSENSE_SLOT_RECORRIDO

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY \
    NEXT_PUBLIC_TELEGRAM_BOT_USERNAME=$NEXT_PUBLIC_TELEGRAM_BOT_USERNAME \
    NEXT_PUBLIC_CLARITY_PROJECT_ID=$NEXT_PUBLIC_CLARITY_PROJECT_ID \
    NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID \
    NEXT_PUBLIC_USE_STATIC_REFERENCE=$NEXT_PUBLIC_USE_STATIC_REFERENCE \
    NEXT_PUBLIC_CUANDO_API_URL=$NEXT_PUBLIC_CUANDO_API_URL \
    NEXT_PUBLIC_BONDI_API_URL=$NEXT_PUBLIC_BONDI_API_URL \
    NEXT_PUBLIC_PROXY_API_URL=$NEXT_PUBLIC_PROXY_API_URL \
    NEXT_PUBLIC_VAPID_PUBLIC=$NEXT_PUBLIC_VAPID_PUBLIC \
    NEXT_PUBLIC_ADSENSE_SLOT_CONSULTAR=$NEXT_PUBLIC_ADSENSE_SLOT_CONSULTAR \
    NEXT_PUBLIC_ADSENSE_SLOT_ARRIVALS=$NEXT_PUBLIC_ADSENSE_SLOT_ARRIVALS \
    NEXT_PUBLIC_ADSENSE_SLOT_FAVORITOS=$NEXT_PUBLIC_ADSENSE_SLOT_FAVORITOS \
    NEXT_PUBLIC_ADSENSE_SLOT_RECORRIDO=$NEXT_PUBLIC_ADSENSE_SLOT_RECORRIDO

RUN npx next build

# === PASO 3: Imagen final de producción (Cambiamos Bun por Node para estabilidad total) ===
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# Copiar assets estáticos y el build standalone
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

# Ejecutamos con Node para garantizar compatibilidad nativa con Turbopack
CMD ["node", "server.js"]